FROM golang:alpine AS build

RUN apk --no-cache add yarn make git build-base
WORKDIR /src
COPY . .
RUN make build-server

FROM alpine:3.14
RUN apk add -U --no-cache ca-certificates
ENV GODEBUG=netdns=go
ENV WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite
ENV WOODPECKER_DATABASE_DRIVER=sqlite3
ENV XDG_CACHE_HOME=/var/lib/woodpecker
EXPOSE 8000 9000 80 443

COPY --from=build /src/dist/woodpecker-server /bin/

ENTRYPOINT ["/bin/woodpecker-server"]
