FROM golang:alpine AS build

RUN apk --no-cache add make git
WORKDIR /src
COPY . .
RUN make build-agent

FROM alpine:3.19
RUN apk add -U --no-cache ca-certificates
ENV GODEBUG=netdns=go
EXPOSE 3000

COPY --from=build /src/dist/woodpecker-agent /bin/

HEALTHCHECK CMD ["/bin/woodpecker-agent", "ping"]
ENTRYPOINT ["/bin/woodpecker-agent"]
